// Generated by gencpp from file ex2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef EX2_MESSAGE_ADDTWOINTS_H
#define EX2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ex2/AddTwoIntsRequest.h>
#include <ex2/AddTwoIntsResponse.h>


namespace ex2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ex2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ex2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ex2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ex2::AddTwoInts > {
  static const char* value()
  {
    return "ex2/AddTwoInts";
  }

  static const char* value(const ::ex2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ex2::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::ex2::AddTwoInts > 
template<>
struct MD5Sum< ::ex2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ex2::AddTwoInts >::value();
  }
  static const char* value(const ::ex2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex2::AddTwoIntsRequest> should match 
// service_traits::DataType< ::ex2::AddTwoInts > 
template<>
struct DataType< ::ex2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ex2::AddTwoInts >::value();
  }
  static const char* value(const ::ex2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ex2::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::ex2::AddTwoInts > 
template<>
struct MD5Sum< ::ex2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ex2::AddTwoInts >::value();
  }
  static const char* value(const ::ex2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex2::AddTwoIntsResponse> should match 
// service_traits::DataType< ::ex2::AddTwoInts > 
template<>
struct DataType< ::ex2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ex2::AddTwoInts >::value();
  }
  static const char* value(const ::ex2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EX2_MESSAGE_ADDTWOINTS_H
